name: 'Create Deployment'
description: 'Create a GitHub deployment and set status to in_progress'
inputs:
  environment:
    description: 'Deployment environment name'
    required: true
outputs:
  deployment-id:
    description: 'The created deployment ID'
    value: ${{ steps.create-deployment.outputs.result }}
runs:
  using: 'composite'
  steps:
    - name: Create deployment
      uses: actions/github-script@v7
      id: create-deployment
      with:
        script: |
          const deployment = await github.rest.repos.createDeployment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: context.sha,
            environment: '${{ inputs.environment }}',
            auto_merge: false,
            required_contexts: []
          });
          
          await github.rest.repos.createDeploymentStatus({
            owner: context.repo.owner,
            repo: context.repo.repo,
            deployment_id: deployment.data.id,
            state: 'in_progress',
            description: 'Deployment started'
          });
          
          return deployment.data.id;