name: 'Docker Build and Push'
description: 'Setup Docker Buildx, login to GitHub Container Registry, and build/push Docker image'
inputs:
  context:
    description: 'Build context path'
    required: false
    default: '.'
  dockerfile:
    description: 'Path to Dockerfile'
    required: true
  image-name:
    description: 'Image name (without registry prefix)'
    required: true
  platforms:
    description: 'Platforms to build for (comma-separated)'
    required: false
    default: 'linux/amd64,linux/arm64'
runs:
  using: 'composite'
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}

    - name: Build and push Docker image (with cache)
      uses: docker/build-push-action@v5
      with:
        context: ${{ inputs.context }}
        file: ${{ inputs.dockerfile }}
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/${{ inputs.image-name }}:latest
          ghcr.io/${{ github.repository_owner }}/${{ inputs.image-name }}:${{ github.sha }}
        platforms: ${{ inputs.platforms }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
