name: 'Update Deployment Status'
description: 'Update GitHub deployment status'
inputs:
  deployment-id:
    description: 'The deployment ID to update'
    required: true
  state:
    description: 'Deployment state (success, failure, error, inactive, etc.)'
    required: true
  description:
    description: 'Status description'
    required: false
    default: ''
  environment-url:
    description: 'Environment URL (for success state)'
    required: false
    default: ''
runs:
  using: 'composite'
  steps:
    - name: Update deployment status
      uses: actions/github-script@v7
      with:
        script: |
          const params = {
            owner: context.repo.owner,
            repo: context.repo.repo,
            deployment_id: '${{ inputs.deployment-id }}',
            state: '${{ inputs.state }}',
            description: '${{ inputs.description }}'
          };
          
          if ('${{ inputs.environment-url }}') {
            params.environment_url = '${{ inputs.environment-url }}';
          }
          
          await github.rest.repos.createDeploymentStatus(params);